name: Aandal-Vanger
favicon: null
layout_spectrum: 0.5728793
typography_spectrum: 0.2072879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6E91AB'
    - '#D8DFDF'
    - '#6E7677'
    - '#39434B'
    - '#161E20'
  brandStrength: 0.1731249
  lightness: 0.1167105
  saturation: 0.6522915
  rhythmicContrast: 0.5704669
purpose: []
